version: '3'
services:

  haskell:
    build: ./server
    container_name: 'hello-haskell'
    tty: true
    volumes:
      - ./server:/app/server
    working_dir: /app/server
    ports:
      - 8080:8080


