org: yukimiyatake
app: elden-talk
service: EldenTalk
frameworkVersion: '3'

custom:
  tableName: 'elden-talk-${sls:stage}'
  defaultStage: dev
  dynamodb:
    docker: true
    stages:
      - dev
    start:
#      inMemory: true
      migrate: true

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, 'ap-northeast-1'}
#  region: 'localhost'
#  profile: ${env:AWS_PROFILE, 'ap-northeast-1'}
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ ConnectionsTable, Arn ]
  environment:
    TABLE_NAME: ${self:custom.tableName}
#      Ref: ConnectionsTable
  websocketsApiName: ${self:service}
  websocketsApiRouteSelectionExpression: $request.body.message

functions:
  connect:
    handler: onconnect/app.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: ondisconnect/app.handler
    events:
      - websocket:
          route: $disconnect
  sendmessage:
    handler: sendmessage/app.handler
    events:
      - websocket:
          route: sendmessage

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
#        ProvisionedThroughput:
#          ReadCapacityUnits: 5
#          WriteCapacityUnits: 5
        SSESpecification:
          SSEEnabled: True


plugins:
#  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

useDotenv: true