#org: yukimiyatake
app: emoy-waitinglist
service: emoy-waitinglist
frameworkVersion: '3'

custom:
  manageTableName: emoy-manage-${sls:stage}
  connectionTableName: ${self:service}-connection-${sls:stage}
  logTableName: ${self:service}-log-${sls:stage}
  defaultStage: dev
  dynamodb:
#    docker: true
    stages:
      - dev
    start:
#      inMemory: true
      migrate: true
#useDotenv: true

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !Sub "${ManageTable.Arn}"  ###
            - !Sub "${ConnectionTable.Arn}"
            - !Sub "${LogTable.Arn}"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !Sub "${ManageTable.Arn}/index/" 
            - !Sub "${ConnectionTable.Arn}/index/"
            - !Sub "${LogTable.Arn}/index/"


  environment:
    APP_MANAGE_TABLE_NAME: ${self:custom.manageTableName}
    APP_CONNECTION_TABLE_NAME: ${self:custom.connectionTableName}
    APP_LOG_TABLE_NAME: ${self:custom.logTableName}
  websocketsApiName: ${self:service}
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  connect:
    handler: src/onconnect/app.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: src/ondisconnect/app.handler
    events:
      - websocket:
          route: $disconnect
  sendmessage:
    handler: src/sendmessage/app.handler
    events:
      - websocket:
          route: sendmessage

resources:
  Resources:
    ManageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.manageTableName}
        AttributeDefinitions:
          - AttributeName: admin
            AttributeType: S
          - AttributeName: appname
            AttributeType: S
        KeySchema:
          - AttributeName: admin
            KeyType: HASH
          - AttributeName: appname
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: True
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.connectionTableName}
        AttributeDefinitions:
          - AttributeName: admin
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: admin
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: True
    LogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.logTableName}
        AttributeDefinitions:
          - AttributeName: admin
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: admin
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: True

plugins:
#  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
