version: '3.8'
services:
  serverless:
    build: 
      context: ./server
      args: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
    stdin_open: true
    image: eldentalk-server
    working_dir: /app
    volumes:
      - .:/app
    container_name: eldentalk-server
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"